export const ErrorCodes = {
  WORKSPACE_NOT_FOUND: "WORKSPACE_NOT_FOUND",
  NOT_WORKSPACE_MEMBER: "NOT_WORKSPACE_MEMBER",
  INSUFFICIENT_ROLE: "INSUFFICIENT_ROLE",
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  MEMBER_NOT_FOUND: "MEMBER_NOT_FOUND",
  ALREADY_A_MEMBER: "ALREADY_A_MEMBER",
  CANNOT_REMOVE_OWNER: "CANNOT_REMOVE_OWNER",
  CANNOT_CHANGE_OWNER_ROLE: "CANNOT_CHANGE_OWNER_ROLE",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
